name: Profil Vert Auto

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Configuration de l'identité Git
        run: |
          git config --global user.name "wassimben2"
          git config --global user.email "wassimbennamane6@gmail.com"
      
      - name: Premier Commit
        run: |
          echo "Update 1 $(date)" >> activite.txt
          git add activite.txt
          git commit -m "update profile stats"
          
      - name: Deuxième Commit
        run: |
          echo "Update 2 $(date)" >> activite.txt
          git add activite.txt
          git commit -m "update profile stats"
          
      - name: Troisième Commit
        run: |
          echo "Update 3 $(date)" >> activite.txt
          git add activite.txt
          git commit -m "update profile stats"

      - name: Envoyer sur GitHub
        run: git push origin main
